spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: productModule
            uri: lb://product
            predicates:
              - Path=/product/**
          - id: customerModule
            uri: lb://customer
            predicates:
              - Path=/customer/**